@startuml
map BasicCommands {
 git config --global USER.NAME "Jonas Hellgren" => sets name
 git config --global USER.EMAIL "Jonas Hellgren" => sets email
 git config list => shows config settings
 git help config  => shows help about config
 git init  => creates local repo
 git status  => shows status
 git reset FILE  => removes FILE (with path)) from staging area
 git reset   => removes all files from staging area
 git log   => commit history
 git clone <url> <where to clone>  => cloning remote repo, <where to clone> can be . (here)
 git remote -v  => info about remote repo, for ex after cloning it
 git branch -a  => lists all branches, also on remote repos
}

BasicCommands --[hidden]> BasicCommands


@enduml